"""Auto-generated by agents/room_extractor.py — DO NOT HAND-EDIT.
   Re-run `python -m agents.room_extractor` to refresh.
"""
from __future__ import annotations

ROOMS = {
  "living_room": {
    "korean_name": "거실",
    "shape_rect": {
      "width_m": 5.0,
      "depth_m": 4.2,
      "height_m": 2.7
    },
    "walls": {
      "NORTH": {
        "anchors": [
          {
            "name_ko": "TV 받침대",
            "name_en": "TV Console",
            "category": "furniture",
            "wall": "NORTH",
            "position_along_wall_pct": 0.75,
            "depth_from_wall_m": 0.0,
            "dim_w_m": 1.6,
            "dim_d_m": 0.4,
            "dim_h_m": 0.6,
            "material_hint": "pine wood frame, white drawers",
            "confidence": "high",
            "notes": "A large flat-screen TV sits on top of this console."
          }
        ],
        "doors": [],
        "windows": []
      },
      "SOUTH": {
        "anchors": [
          {
            "name_ko": "쇼파",
            "name_en": "Sofa",
            "category": "furniture",
            "wall": "SOUTH",
            "position_along_wall_pct": 0.5,
            "depth_from_wall_m": 0.0,
            "dim_w_m": 2.5,
            "dim_d_m": 0.85,
            "dim_h_m": 0.7,
            "material_hint": "light wood frame, blue fabric cushions",
            "confidence": "high",
            "notes": "Often occupied by a cat and a dog."
          }
        ],
        "doors": [],
        "windows": []
      },
      "EAST": {
        "anchors": [
          {
            "name_ko": "피아노",
            "name_en": "Upright Piano",
            "category": "furniture",
            "wall": "EAST",
            "position_along_wall_pct": 0.25,
            "depth_from_wall_m": 0.0,
            "dim_w_m": 1.45,
            "dim_d_m": 0.6,
            "dim_h_m": 1.2,
            "material_hint": "polished black lacquer",
            "confidence": "high",
            "notes": "Positioned against the northern section of the east wall."
          }
        ],
        "doors": [
          {
            "wall_pos_pct": 0.8,
            "width_m": 0.9,
            "leads_to_room": "main_bathroom"
          }
        ],
        "windows": []
      },
      "WEST": {
        "anchors": [
          {
            "name_ko": "에어컨",
            "name_en": "Air Conditioner",
            "category": "appliance",
            "wall": "WEST",
            "position_along_wall_pct": 0.05,
            "depth_from_wall_m": 0.0,
            "dim_w_m": 0.4,
            "dim_d_m": 0.35,
            "dim_h_m": 1.8,
            "material_hint": "white plastic",
            "confidence": "high",
            "notes": "Tall, freestanding floor unit in the corner, as marked on the floor plan."
          },
          {
            "name_ko": "콘솔 테이블",
            "name_en": "Console Table",
            "category": "furniture",
            "wall": "WEST",
            "position_along_wall_pct": 0.9,
            "depth_from_wall_m": 0.0,
            "dim_w_m": 1.1,
            "dim_d_m": 0.45,
            "dim_h_m": 0.8,
            "material_hint": "dark stained wood, antique style",
            "confidence": "high",
            "notes": "Located in the corner next to the sliding door. A pendulum clock hangs on the wall above it."
          },
          {
            "name_ko": "어항",
            "name_en": "Aquarium",
            "category": "decor",
            "wall": "WEST",
            "position_along_wall_pct": 0.2,
            "depth_from_wall_m": 0.0,
            "dim_w_m": 0.4,
            "dim_d_m": 0.25,
            "dim_h_m": 0.3,
            "material_hint": "glass and plastic",
            "confidence": "high",
            "notes": "Small aquarium on a low stand, next to the south end of the sofa."
          }
        ],
        "doors": [],
        "windows": [
          {
            "wall_pos_pct": 0.55,
            "width_m": 2.0,
            "sill_height_m": 0.0,
            "type": "sliding"
          }
        ]
      }
    },
    "floor_material": "light_wood_laminate",
    "wall_material": "off_white_paint",
    "ceiling_material": "white_paint_with_soffit",
    "notable_freestanding": [
      {
        "name_ko": "고양이 스크래쳐/타워",
        "name_en": "Cat Scratcher/Tree",
        "category": "decor",
        "wall": "FREESTANDING",
        "position_along_wall_pct": 0.0,
        "depth_from_wall_m": 0.0,
        "dim_w_m": 0.6,
        "dim_d_m": 0.5,
        "dim_h_m": 1.0,
        "material_hint": "sisal rope and carpet",
        "confidence": "medium",
        "notes": "Position inferred from floor plan sketch (스크래치/풍오). Exact appearance and location varies, but it's generally near the piano."
      }
    ],
    "confidence": "high",
    "evidence_photos": [
      "2025-10-photo-15.jpg",
      "2025-10-photo-12.jpg",
      "2025-10-photo-11.jpg",
      "2025-10-photo-09.jpg"
    ]
  },
  "kitchen_dining": {
    "korean_name": "주방/식당",
    "shape_rect": {
      "width_m": 4.5,
      "depth_m": 3.8,
      "height_m": 2.7
    },
    "walls": {
      "NORTH": {
        "anchors": [
          {
            "name_ko": "주방 카운터",
            "name_en": "Kitchen Counter",
            "category": "fixture",
            "wall": "NORTH",
            "position_along_wall_pct": 0.5,
            "depth_from_wall_m": 0.0,
            "dim_w_m": 4.5,
            "dim_d_m": 0.6,
            "dim_h_m": 0.9,
            "material_hint": "white solid surface countertop, glossy white cabinets, blue subway tile backsplash",
            "confidence": "high",
            "notes": "L-shaped counter that wraps around to the East wall. Contains sink and stove."
          }
        ],
        "doors": [],
        "windows": [
          {
            "wall_pos_pct": 0.6,
            "width_m": 1.2,
            "sill_height_m": 1.1,
            "type": "regular"
          }
        ]
      },
      "SOUTH": {
        "anchors": [],
        "doors": [],
        "windows": []
      },
      "EAST": {
        "anchors": [
          {
            "name_ko": "냉장고",
            "name_en": "Refrigerator",
            "category": "appliance",
            "wall": "EAST",
            "position_along_wall_pct": 0.9,
            "depth_from_wall_m": 0.0,
            "dim_w_m": 0.95,
            "dim_d_m": 0.9,
            "dim_h_m": 1.8,
            "material_hint": "brushed_stainless_steel",
            "confidence": "high",
            "notes": "Large 4-door model, positioned at the southern end of the east wall, near the opening to the living room."
          }
        ],
        "doors": [],
        "windows": []
      },
      "WEST": {
        "anchors": [],
        "doors": [
          {
            "wall_pos_pct": 0.2,
            "width_m": 0.9,
            "leads_to_room": "grandfathers_room"
          }
        ],
        "windows": []
      }
    },
    "floor_material": "light_wood_laminate",
    "wall_material": "off_white_paint_and_blue_tile",
    "ceiling_material": "white_paint",
    "notable_freestanding": [
      {
        "name_ko": "식탁",
        "name_en": "Dining Table",
        "category": "furniture",
        "wall": "FREESTANDING",
        "position_along_wall_pct": 0.0,
        "depth_from_wall_m": 0.0,
        "dim_w_m": 1.8,
        "dim_d_m": 0.9,
        "dim_h_m": 0.75,
        "material_hint": "light wood frame with glass top, mismatched wood chairs",
        "confidence": "high",
        "notes": "Centrally located in the space between the kitchen counter and the living room opening."
      }
    ],
    "confidence": "high",
    "evidence_photos": [
      "2025-10-photo-24.jpg",
      "2025-10-photo-17.jpg",
      "2025-10-photo-16.jpg"
    ]
  }
}

ROOM_CONNECTIONS = [
  {
    "from": "living_room",
    "to": "kitchen_dining",
    "via": "opening",
    "wall_of_from": "NORTH",
    "width_m": 2.8
  },
  {
    "from": "living_room",
    "to": "main_bathroom",
    "via": "door",
    "wall_of_from": "EAST",
    "width_m": 0.9
  },
  {
    "from": "kitchen_dining",
    "to": "grandfathers_room",
    "via": "door",
    "wall_of_from": "WEST",
    "width_m": 0.9
  }
]

GLOBAL_NOTES = [
  "Cardinal directions are based on the floor plan, with the top of the drawing oriented as NORTH.",
  "This model focuses on the Living Room and Kitchen/Dining areas as requested. Other rooms from the floor plan (bedrooms, other bathrooms, utility rooms) are omitted.",
  "Ceiling height is assumed to be a standard 2.7 meters.",
  "The entryway (현관) is treated as a nook off the EAST side of the living room and not modeled as a separate room."
]
